feat(merge): ✨ Add WSL support for installing `wslu`
- Enhanced the `run_onchange_install-packages.sh.tmpl` script to install `wslu` for WSL utilities.
- This addition improves the setup process for users running the script in a WSL environment.

diff --git a/run_onchange_install-packages.sh.tmpl b/run_onchange_install-packages.sh.tmpl
--- a/run_onchange_install-packages.sh.tmpl
+++ b/run_onchange_install-packages.sh.tmpl
@@ -61,6 +61,12 @@ PKG_LIST=(
 echo "Installing APT packages..."
 sudo apt-get install -y -qq "${PKG_LIST[@]}"
 
+if [ "$IS_WSL" = true ]; then
+	# install wslu for WSL utilities
+	echo "WSL: Installing wslu..."
+	sudo apt-get install -y -qq wslu
+fi
+
 # --- Shell Setup ---
 CURRENT_SHELL_PATH=$(getent passwd "$USER" | cut -d: -f7 2>/dev/null || echo $SHELL)
 TARGET_SHELL_PATH=$(command -v zsh)
@@ -139,7 +145,9 @@ if command -v mise &>/dev/null; then
 	if [ -f "$MISE_GLOBAL_CONFIG_FILE" ]; then
 		mise trust "$MISE_GLOBAL_CONFIG_FILE"
 	fi
-	mise install
+	# if already authenticated with gh, pass the token to mise
+	GITHUB_TOKEN=$(gh auth token 2>/dev/null || echo "")
+	mise install || log_error "Mise installation failed."
 
 	echo "Configuring system-wide access for mise..."
 	# 1. Symlink mise binary to /usr/local/bin
